"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BriefcaseBusiness, Plus, Save, Search, Sparkles, Trash2, Users } from "lucide-react";

type ClientProfile = { id:string; name:string; description:string; sector:string; chains:string; topics:string; competitors:string; audience:string; tone:string; objectives:string; avoid:string };
type Story = { headline:string; category:string; score:number; summary:string; reason:string; source_details?:{name:string;url:string;published_at:string}[] };
const blank:ClientProfile={id:"",name:"",description:"",sector:"",chains:"",topics:"",competitors:"",audience:"",tone:"Technical, authoritative, clear",objectives:"Thought leadership, awareness, PR opportunities",avoid:"Unverified claims, price predictions, hype"};

export default function ClientMode(){
 const [clients,setClients]=useState<ClientProfile[]>([]),[activeId,setActiveId]=useState(""),[form,setForm]=useState(blank),[editing,setEditing]=useState(false),[stories,setStories]=useState<Story[]>([]),[loading,setLoading]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{try{const c=JSON.parse(localStorage.getItem("cryptopulse-clients")||"[]");setClients(Array.isArray(c)?c:[]);setActiveId(localStorage.getItem("cryptopulse-active-client")||"")}catch{}},[]);
 useEffect(()=>{const a=clients.find(c=>c.id===activeId);if(a)setForm(a)},[activeId,clients]);
 const active=useMemo(()=>clients.find(c=>c.id===activeId),[clients,activeId]);
 const update=(key:keyof ClientProfile,value:string)=>setForm(f=>({...f,[key]:value}));
 const save=()=>{if(!form.name.trim())return alert("Add a client name first.");const p={...form,id:form.id||crypto.randomUUID()};const next=clients.some(c=>c.id===p.id)?clients.map(c=>c.id===p.id?p:c):[...clients,p];setClients(next);setActiveId(p.id);setForm(p);setEditing(false);setSaved(true);localStorage.setItem("cryptopulse-clients",JSON.stringify(next));localStorage.setItem("cryptopulse-active-client",p.id);setTimeout(()=>setSaved(false),1500)};
 const create=()=>{setForm({...blank});setEditing(true);setStories([])};
 const select=(id:string)=>{setActiveId(id);localStorage.setItem("cryptopulse-active-client",id);setEditing(false);setStories([])};
 const remove=(id:string)=>{if(!confirm("Delete this client profile?"))return;const next=clients.filter(c=>c.id!==id);setClients(next);const id2=next[0]?.id||"";setActiveId(id2);localStorage.setItem("cryptopulse-clients",JSON.stringify(next));localStorage.setItem("cryptopulse-active-client",id2);if(!id2)setForm(blank)};
 const research=async()=>{if(!active)return alert("Select or save a client profile first.");setLoading(true);setStories([]);try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientProfile:active})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Research failed");setStories(j.stories||[])}catch(e){alert(e instanceof Error?e.message:"Unable to research client")}finally{setLoading(false)}};
 return <main style={{minHeight:"100vh",background:"#f7f9fc",color:"#152033",fontFamily:"Inter,system-ui,sans-serif"}}><style>{`.cm-wrap{max-width:1200px;margin:auto;padding:28px}.cm-grid{display:grid;grid-template-columns:270px 1fr;gap:20px}.cm-card{background:#fff;border:1px solid #e4e9f0;border-radius:16px;box-shadow:0 8px 30px rgba(25,40,65,.06)}.cm-btn{border:1px solid #dbe2eb;background:#fff;border-radius:9px;padding:9px 12px;display:inline-flex;align-items:center;gap:7px;cursor:pointer;font-weight:600;color:#243047}.cm-primary{background:#2563eb;color:#fff;border-color:#2563eb}.cm-input{width:100%;box-sizing:border-box;border:1px solid #dbe2eb;border-radius:9px;padding:10px 12px;font:inherit}.cm-label{display:block;font-size:12px;font-weight:700;color:#59677d;margin-bottom:6px}.cm-field{margin-bottom:13px}.cm-client{padding:12px;border-radius:10px;cursor:pointer;margin-bottom:6px}.cm-client.active{background:#edf4ff;border:1px solid #c9dcff}.cm-tag{font-size:11px;background:#f0f4f8;padding:5px 8px;border-radius:999px;color:#506078}.cm-story{padding:17px 0;border-top:1px solid #edf0f4}.cm-score{font-size:21px;font-weight:800;color:#2563eb}@media(max-width:800px){.cm-grid{grid-template-columns:1fr}.cm-wrap{padding:16px}}`}</style><div className="cm-wrap">
 <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap",marginBottom:22}}><div><a href="/" style={{color:"#536174",textDecoration:"none",fontSize:13}}><ArrowLeft size={13} style={{verticalAlign:"-2px"}}/> Back to CryptoPulse</a><div style={{display:"flex",alignItems:"center",gap:10,marginTop:8}}><div style={{width:38,height:38,borderRadius:11,background:"#2563eb",color:"white",display:"grid",placeItems:"center"}}><BriefcaseBusiness size={20}/></div><div><h1 style={{margin:0,fontSize:25}}>Client Mode</h1><p style={{margin:"3px 0 0",color:"#647187",fontSize:13}}>Client-specific research, priorities and PR angles.</p></div></div></div><div style={{display:"flex",gap:8}}><button className="cm-btn" onClick={create}><Plus size={14}/> New client</button>{active&&<button className="cm-btn cm-primary" onClick={research} disabled={loading}><Search size={14}/>{loading?"Researching…":"Research client"}</button>}</div></div>
 <div className="cm-grid"><aside className="cm-card" style={{padding:15,height:"fit-content"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><strong>Clients</strong><span style={{color:"#758197",fontSize:12}}>{clients.length}</span></div>{!clients.length&&<div style={{padding:"20px 5px",color:"#778398",fontSize:13}}>Create your first client.</div>}{clients.map(c=><div key={c.id} className={`cm-client ${activeId===c.id?"active":""}`} onClick={()=>select(c.id)}><div style={{fontWeight:700,fontSize:13}}>{c.name}</div><div style={{fontSize:11,color:"#778398",marginTop:3}}>{c.sector||"Web3 client"}</div></div>)}</aside>
 <section className="cm-card" style={{padding:22}}>{!active&&!editing&&<div style={{padding:"65px 20px",textAlign:"center"}}><Users size={34} color="#7b8798"/><h2>Create a client profile</h2><p style={{color:"#6c788b",maxWidth:520,margin:"0 auto 18px"}}>Tell CryptoPulse who the client is, what they care about, who they compete with and what claims to avoid. Research will use this context to rank opportunities.</p><button className="cm-btn cm-primary" onClick={create}><Plus size={14}/> Create profile</button></div>}
 {editing&&<div><div style={{display:"flex",justifyContent:"space-between",marginBottom:18}}><div><h2 style={{margin:0}}>{form.id?"Edit client":"New client"}</h2><p style={{color:"#758197",fontSize:13}}>These rules guide client-specific research.</p></div><button className="cm-btn" onClick={()=>setEditing(false)}>Cancel</button></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 16px"}}><Field label="Client / brand name" value={form.name} onChange={v=>update("name",v)} placeholder="Acme Protocol"/><Field label="Sector" value={form.sector} onChange={v=>update("sector",v)} placeholder="DeFi, AI, L2…"/><Field label="Chains / ecosystems" value={form.chains} onChange={v=>update("chains",v)} placeholder="Ethereum, Base, Solana…"/><Field label="Target audience" value={form.audience} onChange={v=>update("audience",v)} placeholder="Founders, investors, developers…"/><Field label="Priority topics" value={form.topics} onChange={v=>update("topics",v)} placeholder="Stablecoins, DeFi, agents…"/><Field label="Competitors" value={form.competitors} onChange={v=>update("competitors",v)} placeholder="Competitor A, Competitor B…"/></div><Field label="Brand description" value={form.description} onChange={v=>update("description",v)} placeholder="What does the client do?" area/><Field label="Content tone" value={form.tone} onChange={v=>update("tone",v)} placeholder="Technical, authoritative…" area/><Field label="PR objectives" value={form.objectives} onChange={v=>update("objectives",v)} placeholder="Thought leadership, launches…" area/><Field label="Avoid / guardrails" value={form.avoid} onChange={v=>update("avoid",v)} placeholder="Unverified claims, hype…" area/><button className="cm-btn cm-primary" onClick={save}><Save size={14}/>{saved?"Saved":"Save client profile"}</button></div>}
 {active&&!editing&&<div><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start"}}><div><div style={{display:"flex",gap:8,alignItems:"center"}}><h2 style={{margin:0}}>{active.name}</h2><span className="cm-tag">Active</span></div><p style={{color:"#68758a"}}>{active.description||"No description added."}</p></div><div style={{display:"flex",gap:7}}><button className="cm-btn" onClick={()=>{setForm(active);setEditing(true)}}>Edit</button><button className="cm-btn" onClick={()=>remove(active.id)}><Trash2 size={13}/></button></div></div><div style={{display:"flex",gap:6,flexWrap:"wrap",margin:"15px 0"}}>{[active.sector,...active.chains.split(","),...active.topics.split(",")].filter(Boolean).map((x,i)=><span className="cm-tag" key={i}>{x.trim()}</span>)}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Info title="Audience" value={active.audience}/><Info title="Tone" value={active.tone}/><Info title="Objectives" value={active.objectives}/><Info title="Guardrails" value={active.avoid}/></div><div style={{marginTop:22,borderTop:"1px solid #edf0f4",paddingTop:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h3 style={{margin:0}}>Client intelligence</h3><p style={{margin:"4px 0",color:"#758197",fontSize:12}}>Latest stories ranked for this client.</p></div><button className="cm-btn cm-primary" onClick={research} disabled={loading}><Sparkles size={13}/>{loading?"Researching…":"Run research"}</button></div>{loading&&<p style={{color:"#68758a"}}>Finding recent stories relevant to {active.name}…</p>}{!loading&&!stories.length&&<p style={{padding:"25px 0",textAlign:"center",color:"#788498"}}>Run research to populate opportunities.</p>}{stories.map((s,i)=><div className="cm-story" key={i}><div style={{display:"flex",justifyContent:"space-between",gap:15}}><div><span className="cm-tag">{s.category}</span><h3 style={{margin:"8px 0 5px"}}>{s.headline}</h3><p style={{margin:0,color:"#637086",fontSize:13,lineHeight:1.55}}>{s.summary}</p></div><div className="cm-score">{s.score}</div></div><p style={{fontSize:12,color:"#59677d"}}><strong>Why it matters:</strong> {s.reason}</p>{s.source_details?.length?<div style={{fontSize:11,color:"#748096"}}>Sources: {s.source_details.map((src,j)=><span key={j}>{j?" · ":""}{src.name||"Source"}{src.published_at?` · ${new Date(src.published_at).toLocaleDateString()}`:""}</span>)}</div>:null}</div>)}</div></div>}</section></div></div></main>;
}
function Field({label,value,onChange,placeholder,area=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;area?:boolean}){return <div className="cm-field" style={area?{gridColumn:"1/-1"}:undefined}><label className="cm-label">{label}</label>{area?<textarea className="cm-input" rows={3} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>:<input className="cm-input" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</div>}
function Info({title,value}:{title:string;value:string}){return <div style={{background:"#f7f9fc",border:"1px solid #edf0f4",borderRadius:11,padding:12}}><div style={{fontSize:10,textTransform:"uppercase",letterSpacing:.5,color:"#7b8798",fontWeight:700}}>{title}</div><div style={{fontSize:12,color:"#344156",marginTop:5}}>{value||"Not set"}</div></div>}
