create table if not exists public.linkedin_connection (
  id integer primary key default 1 check (id = 1),
  person_urn text not null,
  name text,
  access_token text not null,
  refresh_token text,
  access_token_expires_at timestamptz not null,
  refresh_token_expires_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.linkedin_posts (
  id bigint generated by default as identity primary key,
  topic text not null,
  content text not null,
  linkedin_post_id text not null,
  created_at timestamptz not null default now()
);

alter table public.linkedin_connection enable row level security;
alter table public.linkedin_posts enable row level security;
