import { runResearch, type ResearchItem, type Narrative } from "@/lib/research-engine";

type AgentStatus = "completed" | "degraded";
export type AgentReport = { name:string; role:string; status:AgentStatus; findings:string[]; itemIds:string[] };
export type MultiAgentPacket = { generated_at_utc:string; current_date:string; candidates:ResearchItem[]; narratives:Narrative[]; agents:AgentReport[]; priority_focus:string[]; verification:{verified:number;needs_review:number;rejected:number}; source_health:Array<{name:string;discovered:number;status:string;url:string}>; raw_candidate_count:number; fresh_candidate_count:number };
const PRIORITY=["Exploits & Hacks","Airdrops","Airdrop Guides"];
const FALLBACK=["AI & Agentic","DeFi","Ethereum","Bitcoin","Infrastructure","Institutions","Regulation","Memecoins","Emerging"];
const securityTerms=/(exploit|hack|hacked|drain|drained|attack|vulnerability|vulnerable|breach|stolen|flash loan|bridge attack|private key|contract bug)/i;
const airdropTerms=/(airdrop|airdrop campaign|token claim|claim window|snapshot|points program|retroactive|testnet|quest|points|eligib)/i;
const aiTerms=/(\bai\b|artificial intelligence|agentic|ai agent|ai agents|autonomous agent|machine learning|inference|llm|model)/i;
const defiTerms=/(defi|dex|lending|borrow|yield|liquidity|amm|perps|perpetual|stablecoin)/i;
const marketTerms=/(bitcoin|btc|ethereum|eth|solana|sol|price|market|etf|fund|institution|treasury|inflow|outflow)/i;
const regulatoryTerms=/(regulation|regulator|sec|cftc|law|bill|legislation|policy|court|compliance|license)/i;
function top(items:ResearchItem[],predicate:(item:ResearchItem)=>boolean,limit=8){return items.filter(predicate).sort((a,b)=>b.scores.overall-a.scores.overall).slice(0,limit)}
function report(name:string,role:string,selected:ResearchItem[],findings:string[]):AgentReport{return {name,role,status:selected.length?"completed":"degraded",findings,itemIds:selected.map(i=>i.id)}}
function scoutAgent(items:ResearchItem[]):AgentReport{const selected=items.slice().sort((a,b)=>b.scores.overall-a.scores.overall).slice(0,20);return report("Scout Agent","Find fresh high-signal Web3 developments",selected,[`Reviewed ${items.length} fresh research candidates.`,`Shortlisted ${selected.length} highest-scoring candidates for specialist review.`])}
function airdropAgent(items:ResearchItem[]):AgentReport{const selected=top(items,i=>i.category==="Airdrops"||i.category==="Airdrop Guides"||airdropTerms.test(`${i.title} ${i.summary}`));return report("Airdrop Agent","Detect actionable airdrops, claims, points, quests and guides",selected,[`Found ${selected.length} airdrop-related candidates.`,selected[0]?`Top opportunity: ${selected[0].title}`:"No current airdrop opportunity met the freshness filter."])}
function securityAgent(items:ResearchItem[]):AgentReport{const selected=top(items,i=>i.category==="Exploits & Hacks"||securityTerms.test(`${i.title} ${i.summary}`));return report("Security Agent","Detect exploits, hacks, vulnerabilities and user-impacting incidents",selected,[`Found ${selected.length} security-related candidates.`,selected[0]?`Top security signal: ${selected[0].title}`:"No current security incident met the freshness filter."])}
function socialAgent(items:ResearchItem[]):AgentReport{const selected=items.filter(i=>i.source==="Reddit"||i.source==="X").sort((a,b)=>(b.community?.score||0)-(a.community?.score||0)).slice(0,15);return report("Social Signal Agent","Combine Reddit and X web signals into narrative momentum",selected,[`Collected ${selected.length} social-signal candidates.`,`Highest social signal: ${selected[0]?.community?.score??0}/100.`])}
function aiAgent(items:ResearchItem[]):AgentReport{const selected=top(items,i=>i.category==="AI & Agentic"||aiTerms.test(`${i.title} ${i.summary}`));return report("AI & Agentic Agent","Find fresh AI, agentic AI and autonomous-agent developments in Web3",selected,[`Found ${selected.length} AI/agentic candidates.`,selected[0]?`Top AI/agentic signal: ${selected[0].title}`:"No current AI/agentic opportunity met the freshness filter."])}
function defiAgent(items:ResearchItem[]):AgentReport{const selected=top(items,i=>i.category==="DeFi"||defiTerms.test(`${i.title} ${i.summary}`));return report("DeFi Agent","Track DeFi protocols, liquidity, lending, DEXs, perps and stablecoin developments",selected,[`Found ${selected.length} DeFi candidates.`,selected[0]?`Top DeFi signal: ${selected[0].title}`:"No current DeFi signal met the freshness filter."])}
function marketsAgent(items:ResearchItem[]):AgentReport{const selected=top(items,i=>["Bitcoin","Ethereum","Markets"].includes(i.category)||marketTerms.test(`${i.title} ${i.summary}`));return report("Markets Agent","Track Bitcoin, Ethereum, market structure, ETF, flows and institutional signals",selected,[`Found ${selected.length} market candidates.`,selected[0]?`Top market signal: ${selected[0].title}`:"No current market signal met the freshness filter."])}
function regulationAgent(items:ResearchItem[]):AgentReport{const selected=top(items,i=>i.category==="Regulation"||regulatoryTerms.test(`${i.title} ${i.summary}`));return report("Policy & Regulation Agent","Track regulators, legislation, courts, licensing and policy changes",selected,[`Found ${selected.length} policy/regulation candidates.`,selected[0]?`Top policy signal: ${selected[0].title}`:"No current policy signal met the freshness filter."])}
async function verificationAgent(items:ResearchItem[]):Promise<{report:AgentReport;verified:number;needs_review:number;rejected:number}>{const verified:ResearchItem[]=[];const review:ResearchItem[]=[];const rejected:ResearchItem[]=[];for(const item of items){const date=new Date(item.publishedAt).getTime();const fresh=Number.isFinite(date)&&date>=Date.now()-72*60*60*1000&&date<=Date.now()+15*60*1000;const hasSource=Boolean(item.url&&item.source);if(!fresh||!hasSource)rejected.push(item);else if(item.source==="Reddit"||item.source==="X")review.push(item);else verified.push(item)}const accepted=[...verified,...review];return {report:report("Verification Agent","Gate freshness, provenance, source quality and risk before content generation",accepted,[`Verified ${verified.length} candidates from attributable sources.`,`${review.length} social-signal candidates require source confirmation before publication.`,`Rejected ${rejected.length} stale or incomplete candidates.`]),verified:verified.length,needs_review:review.length,rejected:rejected.length}}
function trendAgent(items:ResearchItem[],narratives:Narrative[]):AgentReport{const selected=items.slice().sort((a,b)=>b.scores.overall-a.scores.overall).slice(0,15);return report("Trend & Narrative Agent","Identify emerging narratives, momentum and cross-source themes",selected,[`Analyzed ${items.length} candidates for narrative momentum.`,narratives.slice(0,5).map(n=>n.name).join(", ")?`Leading narratives: ${narratives.slice(0,5).map(n=>n.name).join(", ")}.`:"No dominant narrative was detected."])}
function strategistAgent(items:ResearchItem[]):{report:AgentReport;selected:ResearchItem[]}{
  const available=items.slice();const selected:ResearchItem[]=[];const selectedIds=new Set<string>();
  // Deliberately seed the reserve with different categories. This prevents a single hack/airdrop
  // narrative from occupying every top slot and gives the Content Director genuinely distinct inputs.
  const lanes:Array<{name:string;match:(i:ResearchItem)=>boolean}>= [
    {name:"Exploits & Hacks",match:i=>i.category==="Exploits & Hacks"||securityTerms.test(`${i.title} ${i.summary}`)},
    {name:"Airdrops",match:i=>i.category==="Airdrops"||i.category==="Airdrop Guides"||airdropTerms.test(`${i.title} ${i.summary}`)},
    {name:"AI & Agentic",match:i=>i.category==="AI & Agentic"||aiTerms.test(`${i.title} ${i.summary}`)},
    {name:"DeFi",match:i=>i.category==="DeFi"||defiTerms.test(`${i.title} ${i.summary}`)},
    {name:"Markets",match:i=>["Bitcoin","Ethereum","Markets"].includes(i.category)||marketTerms.test(`${i.title} ${i.summary}`)},
    {name:"Regulation",match:i=>i.category==="Regulation"||regulatoryTerms.test(`${i.title} ${i.summary}`)},
    {name:"Infrastructure",match:i=>i.category==="Infrastructure"},
    {name:"Emerging",match:i=>i.category==="Emerging"||i.category==="Memecoins"},
  ];
  for(const lane of lanes){const candidate=available.filter(i=>!selectedIds.has(i.id)&&lane.match(i)).sort((a,b)=>b.scores.overall-a.scores.overall)[0];if(candidate){selected.push(candidate);selectedIds.add(candidate.id)}}
  for(const item of available.slice().sort((a,b)=>b.scores.overall-a.scores.overall)){if(selected.length>=40)break;if(selectedIds.has(item.id))continue;selected.push(item);selectedIds.add(item.id)}
  return {selected,report:report("Strategist Agent","Build the final opportunity pool with priority lanes, diversity and publication potential",selected,[`Reviewed ${available.length} verified candidates.`,`Seeded ${Math.min(8,selected.length)} distinct narrative lanes before score-ranked backfill.`,`Built a ${selected.length}-candidate reserve for downstream memory filtering and content generation.`,`First-pass category diversity is enforced so the Content Director receives different real-world opportunities.`])}
}
export async function runMultiAgentResearch(_excludedIds:string[]=[]):Promise<MultiAgentPacket>{const research=await runResearch();const items=research.items;const scout=scoutAgent(items);const airdrop=airdropAgent(items);const security=securityAgent(items);const social=socialAgent(items);const ai=aiAgent(items);const defi=defiAgent(items);const markets=marketsAgent(items);const regulation=regulationAgent(items);const trend=trendAgent(items,research.narratives);const verification=await verificationAgent(items);const verifiedItems=items.filter(item=>verification.report.itemIds.includes(item.id));const strategy=strategistAgent(verifiedItems);return {generated_at_utc:research.generatedAt,current_date:research.generatedAt.slice(0,10),candidates:strategy.selected,narratives:research.narratives,agents:[scout,airdrop,security,social,ai,defi,markets,regulation,trend,verification.report,strategy.report],priority_focus:[...PRIORITY,"AI & Agentic","DeFi","Markets","Policy & Regulation"],verification:{verified:verification.verified,needs_review:verification.needs_review,rejected:verification.rejected},source_health:research.sourceHealth||[],raw_candidate_count:research.raw_candidate_count||0,fresh_candidate_count:research.fresh_candidate_count||items.length}}
