export type ResearchItem = {
  id:string; title:string; url:string; source:string; publishedAt:string; summary:string;
  category:string; keywords:string[]; entities:string[];
  scores:{relevance:number;momentum:number;novelty:number;credibility:number;prPotential:number;overall:number};
  opportunity:string;
  community?:{platform:"reddit"|"x";score:number;posts:number;comments:number;sentiment:"bullish"|"bearish"|"neutral";subreddits?:string[];handles?:string[]};
};
export type Narrative={name:string;count:number;score:number;momentum:number;keywords:string[];stories:string[];communityScore?:number;xScore?:number};
const FEEDS=[{name:"CoinDesk",url:"https://www.coindesk.com/arc/outboundfeeds/rss/"},{name:"Cointelegraph",url:"https://cointelegraph.com/rss"},{name:"Decrypt",url:"https://decrypt.co/feed"},{name:"CryptoSlate",url:"https://cryptoslate.com/feed/"},{name:"The Block",url:"https://www.theblock.co/rss.xml"}];
// Keep the source pool broad. The duplicate guard belongs to content-memory.ts; research
// should not throw away genuinely different stories merely because their headlines share
// common Web3 vocabulary.
const GOOGLE_NEWS=[
  "crypto Web3 breaking news","crypto airdrop points claim eligibility","crypto exploit hack security",
  "Ethereum Bitcoin DeFi latest","crypto AI agentic Web3","crypto regulation stablecoin institutions",
  "Solana latest crypto news","Base latest crypto news","Arbitrum Optimism layer 2 latest",
  "stablecoin payments crypto latest","DeFi protocol launch funding partnership crypto",
  "Bitcoin institutional ETF flows latest","Ethereum upgrade L2 latest","crypto startup funding Web3 latest",
  "memecoin token launch crypto latest","onchain crypto adoption infrastructure latest"
];
const REDDIT_SUBREDDITS=["CryptoCurrency","ethereum","Bitcoin","defi","solana","base"];
const MAX_AGE_HOURS=72, SOURCE_TIMEOUT_MS=7000;
const TOPICS:Record<string,string[]>={"Airdrops":["airdrop","claim","points","testnet","quest","eligibility","retroactive"],"Exploits & Hacks":["exploit","hack","hacked","drained","drain","stolen","attack","breach","vulnerability","private key","bridge hack"],"Airdrop Guides":["airdrop guide","how to claim","how to qualify","eligibility","airdrop farming","points campaign","quest"],"AI & Agentic":["agentic","ai agent","ai agents","autonomous agent","artificial intelligence","machine learning","inference","llm"],"DeFi":["defi","lending","dex","yield","liquidity","stablecoin"],"Ethereum":["ethereum","eth","layer 2","l2","rollup","scaling"],"Bitcoin":["bitcoin","btc","halving","ordinals","lightning"],"Regulation":["sec","regulation","regulator","law","policy","legislation","compliance"],"Institutions":["institutional","bank","etf","asset manager","fund","custody"],"Infrastructure":["protocol","mainnet","testnet","upgrade","network","infrastructure"],"Memecoins":["memecoin","meme coin","doge","shib","pepe"]};
const clean=(v:string)=>v.replace(/<[^>]*>/g," ").replace(/<!\[CDATA\[|\]\]>/g," ").replace(/\s+/g," ").trim();
const decode=(v:string)=>v.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">");
const tag=(text:string,name:string)=>{const m=text.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)</${name}>`,"i"));return m?decode(clean(m[1])):"";};
const pub=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toISOString()};
const norm=(v:string)=>v.toLowerCase().replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
function parseFeed(xml:string,source:string):ResearchItem[]{const blocks=xml.match(/<item[\s\S]*?<\/item>/gi)||xml.match(/<entry[\s\S]*?<\/entry>/gi)||[];return blocks.slice(0,100).map((block,index)=>{const title=tag(block,"title"),summary=tag(block,"description")||tag(block,"summary")||tag(block,"content"),publishedAt=pub(tag(block,"pubDate")||tag(block,"published")||tag(block,"updated")||tag(block,"dc:date")),guid=tag(block,"guid")||tag(block,"id")||`${source}-${index}-${title}`,url=block.match(/<link[^>]+href=["']([^"']+)["'][^>]*>/i)?.[1]||tag(block,"link");return{id:`${source}:${Buffer.from(guid).toString("base64url").slice(0,30)}`,title,url,source,publishedAt,summary:summary.slice(0,900),category:"Emerging",keywords:[],entities:[],scores:{relevance:0,momentum:0,novelty:0,credibility:0,prPotential:0,overall:0},opportunity:""};}).filter(x=>x.title&&x.url&&x.publishedAt);}
function classify(i:ResearchItem){const text=`${i.title} ${i.summary}`.toLowerCase(),matches=Object.entries(TOPICS).map(([name,terms])=>({name,hits:terms.filter(t=>text.includes(t))})).filter(x=>x.hits.length).sort((a,b)=>b.hits.length-a.hits.length);i.category=matches[0]?.name||"Emerging";i.keywords=[...new Set(matches.flatMap(x=>x.hits))].slice(0,8);i.entities=["Ethereum","Bitcoin","Solana","Base","Arbitrum","Optimism","Coinbase","Binance","Uniswap","Aave","OpenAI","SEC"].filter(e=>text.includes(e.toLowerCase()));}
function score(i:ResearchItem){classify(i);const text=`${i.title} ${i.summary}`.toLowerCase(),age=Math.max(0,(Date.now()-Date.parse(i.publishedAt))/36e5),recency=Math.max(10,100-age*3),priority=i.category==="Exploits & Hacks"?30:i.category==="Airdrops"?24:i.category==="Airdrop Guides"?20:i.category==="AI & Agentic"?14:0,relevance=Math.min(100,40+i.keywords.length*8+i.entities.length*5+priority),momentum=Math.min(100,Math.round(recency+priority*.35)),credibility=i.source==="CoinDesk"||i.source==="The Block"?90:i.source==="Cointelegraph"?86:i.source==="Decrypt"?82:i.source==="CryptoSlate"?78:i.source==="Reddit"?72:i.source==="Google News"?68:60,pr=Math.min(100,45+(/(launch|funding|upgrade|partnership|approval|adoption|record|surge|integration)/i.test(text)?30:8)+i.entities.length*5+priority*.5);i.scores={relevance,momentum,novelty:75,credibility,prPotential:pr,overall:Math.min(100,Math.round(relevance*.2+momentum*.22+75*.13+credibility*.15+pr*.2))};i.opportunity=i.category==="Exploits & Hacks"?"Urgent security story — verify with a primary source":i.category==="Airdrops"||i.category==="Airdrop Guides"?"High-interest airdrop opportunity — verify eligibility and official links":i.category==="AI & Agentic"?"Fresh AI/agentic Web3 opportunity — verify the underlying source":i.scores.overall>=80?"High-value current opportunity":"Fresh story to monitor";}
async function fetchWithTimeout(url:string,init?:RequestInit){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),SOURCE_TIMEOUT_MS);try{return await fetch(url,{...init,signal:controller.signal})}finally{clearTimeout(timer);}}
function sentiment(t:string):"bullish"|"bearish"|"neutral"{const s=t.toLowerCase(),bull=(s.match(/bullish|pump|breakout|adoption|buy|ath/g)||[]).length,bear=(s.match(/bearish|dump|crash|scam|sell|hack|exploit|drain|stolen/g)||[]).length;return bull>bear?"bullish":bear>bull?"bearish":"neutral";}
async function fetchReddit(){const cutoff=Date.now()-MAX_AGE_HOURS*36e5;const chunks=await Promise.all(REDDIT_SUBREDDITS.map(async sub=>{try{const r=await fetchWithTimeout(`https://www.reddit.com/r/${sub}/new.json?limit=40`,{headers:{"User-Agent":"Web3PulseResearch/1.0"}});if(!r.ok)return [] as ResearchItem[];const j=await r.json(),out:ResearchItem[]=[];for(const child of j?.data?.children||[]){const p=child?.data;if(!p?.title)continue;const created=Number(p.created_utc)*1000;if(!created||created<cutoff||created>Date.now()+15*60e3)continue;out.push({id:`reddit:${p.id}`,title:p.title,url:p.url||`https://www.reddit.com${p.permalink||""}`,source:"Reddit",publishedAt:new Date(created).toISOString(),summary:String(p.selftext||p.title).slice(0,900),category:"Emerging",keywords:[],entities:[],scores:{relevance:0,momentum:0,novelty:0,credibility:72,prPotential:0,overall:0},opportunity:"",community:{platform:"reddit",score:Math.min(100,35+Math.min(40,Number(p.score)||0)*2+Math.min(25,Number(p.num_comments)||0)),posts:1,comments:Number(p.num_comments)||0,sentiment:sentiment(`${p.title} ${p.selftext||""}`),subreddits:[sub]}});}return out;}catch{return [] as ResearchItem[]}}));return chunks.flat();}
async function fetchGoogleNews(){const results=await Promise.all(GOOGLE_NEWS.map(async query=>{try{const r=await fetchWithTimeout(`https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=en-US&gl=US&ceid=US:en`,{headers:{"User-Agent":"Web3PulseResearch/1.0"}});if(!r.ok)return [] as ResearchItem[];return parseFeed(await r.text(),"Google News");}catch{return [] as ResearchItem[]}}));return results.flat();}
function dedupe(items:ResearchItem[]){const result:ResearchItem[]=[];const seenTitles:string[]=[];for(const item of items){const n=norm(item.title);if(!n)continue;const duplicate=seenTitles.some(x=>{const a=new Set(n.split(" ").filter(t=>t.length>=4)),b=new Set(x.split(" ").filter(t=>t.length>=4));let overlap=0;for(const t of a)if(b.has(t))overlap++;const min=Math.min(a.size,b.size);return min>=4&&overlap/min>=0.92;});if(duplicate)continue;seenTitles.push(n);result.push(item);}return result;}
export function detectNarratives(items:ResearchItem[]):Narrative[]{const groups=new Map<string,ResearchItem[]>();for(const i of items)groups.set(i.category,[...(groups.get(i.category)||[]),i]);return [...groups.entries()].map(([name,stories])=>({name,count:stories.length,score:Math.round(stories.reduce((s,i)=>s+i.scores.overall,0)/stories.length),momentum:Math.round(stories.reduce((s,i)=>s+i.scores.momentum,0)/stories.length),communityScore:Math.round(stories.reduce((s,i)=>s+(i.community?.score||0),0)/stories.length),xScore:0,keywords:[...new Set(stories.flatMap(i=>i.keywords))].slice(0,8),stories:stories.slice(0,5).map(i=>i.id)})).sort((a,b)=>b.score-a.score);}
export async function runResearch(){const cutoff=Date.now()-MAX_AGE_HOURS*36e5;const feedResults=await Promise.all(FEEDS.map(async feed=>{try{const r=await fetchWithTimeout(feed.url,{headers:{"User-Agent":"Web3PulseResearch/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return{feed,items:parseFeed(await r.text(),feed.name),status:"connected"};}catch{return{feed,items:[] as ResearchItem[],status:"unavailable"};}}));const redditItems=await fetchReddit();const googleItems=await fetchGoogleNews();const all=[...feedResults.flatMap(x=>x.items),...redditItems,...googleItems].filter(i=>{const t=Date.parse(i.publishedAt);return Number.isFinite(t)&&t>=cutoff&&t<=Date.now()+15*60e3});const unique=dedupe(all);unique.forEach(score);unique.sort((a,b)=>b.scores.overall-a.scores.overall||Date.parse(b.publishedAt)-Date.parse(a.publishedAt));const trending=unique.slice(0,300);const sourceHealth=[...feedResults.map(x=>({name:x.feed.name,discovered:x.items.filter(i=>Date.parse(i.publishedAt)>=cutoff).length,status:x.status,url:x.feed.url})),{name:"Reddit",discovered:redditItems.length,status:redditItems.length?"connected":"unavailable",url:"https://www.reddit.com/"},{name:"Google News",discovered:googleItems.filter(i=>Date.parse(i.publishedAt)>=cutoff).length,status:googleItems.length?"connected":"unavailable",url:"https://news.google.com/"}];return{generatedAt:new Date().toISOString(),items:trending,narratives:detectNarratives(trending),sourceHealth,raw_candidate_count:all.length,fresh_candidate_count:trending.length};}