export type ResearchItem = {
  id: string; title: string; url: string; source: string; publishedAt: string; summary: string; category: string; keywords: string[]; entities: string[];
  scores: { relevance: number; momentum: number; novelty: number; credibility: number; prPotential: number; overall: number };
  opportunity: string; community?: { platform: "reddit"; score: number; posts: number; comments: number; sentiment: "bullish" | "bearish" | "neutral"; subreddits: string[] };
};
export type Narrative = { name: string; count: number; score: number; momentum: number; keywords: string[]; stories: string[]; communityScore?: number };
const FEEDS = [
  { name: "CoinDesk", url: "https://www.coindesk.com/arc/outboundfeeds/rss/" },
  { name: "Cointelegraph", url: "https://cointelegraph.com/rss" },
  { name: "Decrypt", url: "https://decrypt.co/feed" },
];
const REDDIT_SUBREDDITS = ["CryptoCurrency", "ethereum", "Bitcoin", "defi", "solana"];
const MAX_AGE_HOURS = 48;
const TOPICS: Record<string,string[]> = { AI:["ai","agent","agents","artificial intelligence","machine learning"], DeFi:["defi","lending","dex","yield","liquidity","stablecoin"], Ethereum:["ethereum","eth","layer 2","l2","rollup","scaling"], Bitcoin:["bitcoin","btc","halving","ordinals","lightning"], Regulation:["sec","regulation","regulator","law","policy","legislation","compliance"], Institutions:["institutional","bank","etf","asset manager","fund","custody"], Infrastructure:["protocol","mainnet","testnet","upgrade","network","infrastructure"], Memecoins:["memecoin","meme coin","doge","shib","pepe"] };
const strip=(v:string)=>v.replace(/<[^>]*>/g," ").replace(/<!\[CDATA\[|\]\]>/g," ").replace(/\s+/g," ").trim();
const decode=(v:string)=>v.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">");
const between=(text:string,tag:string)=>{const m=text.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)</${tag}>`,"i"));return m?decode(strip(m[1])):""};
function parsePublishedDate(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toISOString()}
function parseFeed(xml:string,source:string):ResearchItem[]{const blocks=xml.match(/<item[\s\S]*?<\/item>/gi)||xml.match(/<entry[\s\S]*?<\/entry>/gi)||[];return blocks.slice(0,50).map((block,index)=>{const title=between(block,"title");const summary=between(block,"description")||between(block,"summary")||between(block,"content");const publishedAt=parsePublishedDate(between(block,"pubDate")||between(block,"published")||between(block,"updated"));const guid=between(block,"guid")||`${source}-${index}-${title}`;const lm=block.match(/<link[^>]*href=["']([^"']+)["'][^>]*>/i);const url=lm?.[1]||between(block,"link")||"";return {id:`${source}:${Buffer.from(guid).toString("base64url").slice(0,28)}`,title,url,source,publishedAt,summary:summary.slice(0,500),category:"Emerging",keywords:[],entities:[],scores:{relevance:0,momentum:0,novelty:0,credibility:0,prPotential:0,overall:0},opportunity:""}}).filter(x=>x.title&&x.url&&x.publishedAt)}
function classify(item:ResearchItem){const text=`${item.title} ${item.summary}`.toLowerCase();const matches=Object.entries(TOPICS).map(([name,terms])=>({name,hits:terms.filter(term=>text.includes(term))})).filter(x=>x.hits.length);matches.sort((a,b)=>b.hits.length-a.hits.length);item.category=matches[0]?.name||"Emerging";item.keywords=Array.from(new Set(matches.flatMap(x=>x.hits))).slice(0,8);const entities=["Ethereum","Bitcoin","Solana","Base","Arbitrum","Optimism","Coinbase","Binance","Uniswap","Aave","OpenAI","SEC"];item.entities=entities.filter(e=>text.includes(e.toLowerCase()))}
function score(item:ResearchItem,duplicateCount:number){classify(item);const text=`${item.title} ${item.summary}`.toLowerCase();const h=Math.max(0,(Date.now()-new Date(item.publishedAt).getTime())/36e5);const recency=Math.max(0,100-h*3.5);const relevance=Math.min(100,45+item.keywords.length*8+item.entities.length*5);const momentum=Math.round(Math.max(20,recency));const novelty=Math.max(25,100-duplicateCount*22);const credibility=item.source==="CoinDesk"?92:item.source==="Cointelegraph"?86:82;const prPotential=Math.min(100,45+( /(launch|launches|raises|funding|upgrade|partnership|acquire|approval|adoption|record|surge|integration)/i.test(text)?30:8)+item.entities.length*5);const community=item.community?.score||0;const overall=Math.round(relevance*.18+momentum*.22+novelty*.13+credibility*.14+prPotential*.23+community*.10);item.scores={relevance,momentum,novelty,credibility,prPotential,overall};item.opportunity=overall>=85?"High-value trending opportunity":overall>=70?"Strong current angle worth reviewing":"Fresh story to monitor"}
function redditSentiment(text:string):"bullish"|"bearish"|"neutral"{const t=text.toLowerCase();const bull=(t.match(/bullish|moon|pump|breakout|adoption|buy|undervalued|ath/g)||[]).length;const bear=(t.match(/bearish|dump|crash|scam|sell|overvalued|hack|exploit/g)||[]).length;return bull>bear?"bullish":bear>bull?"bearish":"neutral"}
async function fetchReddit(){const cutoff=Date.now()-MAX_AGE_HOURS*36e5;const results:ResearchItem[]=[];for(const sub of REDDIT_SUBREDDITS){try{const r=await fetch(`https://www.reddit.com/r/${sub}/new.json?limit=25`,{headers:{"User-Agent":"Web3PulseResearch/1.0"},next:{revalidate:300}});if(!r.ok)continue;const j=await r.json();for(const child of j?.data?.children||[]){const p=child?.data;if(!p?.title||!p?.url)continue;const created=Number(p.created_utc)*1000;if(!created||created<cutoff||created>Date.now()+15*60*1000)continue;results.push({id:`reddit:${p.id}`,title:p.title,url:p.url,source:"Reddit",publishedAt:new Date(created).toISOString(),summary:String(p.selftext||p.title).slice(0,500),category:"Emerging",keywords:[],entities:[],scores:{relevance:0,momentum:0,novelty:0,credibility:72,prPotential:0,overall:0},opportunity:"",community:{platform:"reddit",score:Math.min(100,35+Math.min(40,Number(p.score)||0)*2+Math.min(25,Number(p.num_comments)||0)),posts:1,comments:Number(p.num_comments)||0,sentiment:redditSentiment(`${p.title} ${p.selftext||""}`),subreddits:[sub]}})}}catch{}}return results}
export function detectNarratives(items:ResearchItem[]):Narrative[]{const groups=new Map<string,ResearchItem[]>();for(const item of items){const key=item.category||"Emerging";groups.set(key,[...(groups.get(key)||[]),item])}return Array.from(groups.entries()).map(([name,stories])=>({name,count:stories.length,score:Math.round(stories.reduce((s,i)=>s+i.scores.overall,0)/stories.length),momentum:Math.round(stories.reduce((s,i)=>s+i.scores.momentum,0)/stories.length),communityScore:Math.round(stories.reduce((s,i)=>s+(i.community?.score||0),0)/stories.length),keywords:Array.from(new Set(stories.flatMap(i=>i.keywords))).slice(0,8),stories:stories.slice(0,5).map(i=>i.id)})).sort((a,b)=>(b.communityScore||0)-(a.communityScore||0)||b.momentum-a.momentum||b.score-a.score)}
export async function runResearch(){const [feedResults,redditItems]=await Promise.all([Promise.all(FEEDS.map(async feed=>{try{const r=await fetch(feed.url,{headers:{"User-Agent":"Web3PulseResearch/1.0"},next:{revalidate:300}});if(!r.ok)throw new Error();return {feed,items:parseFeed(await r.text(),feed.name),status:"connected"}}catch{return {feed,items:[],status:"unavailable"}}})),fetchReddit()]);const cutoff=Date.now()-MAX_AGE_HOURS*36e5;const raw=[...feedResults.flatMap(x=>x.items),...redditItems].filter(i=>{const t=new Date(i.publishedAt).getTime();return Number.isFinite(t)&&t>=cutoff&&t<=Date.now()+15*60*1000});const seen=new Map<string,number>();for(const i of raw){const k=i.title.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();seen.set(k,(seen.get(k)||0)+1)}const unique=Array.from(new Map(raw.map(i=>[i.title.toLowerCase().replace(/[^a-z0-9]+/g," ").trim(),i])).values());unique.forEach(i=>score(i,seen.get(i.title.toLowerCase().replace(/[^a-z0-9]+/g," ").trim())||1));unique.sort((a,b)=>b.scores.overall-a.scores.overall||new Date(b.publishedAt).getTime()-new Date(a.publishedAt).getTime());const trending=unique.slice(0,30);return {items:trending,narratives:detectNarratives(trending),sources:[...feedResults.map(x=>({name:x.feed.name,discovered:x.items.filter(i=>new Date(i.publishedAt).getTime()>=cutoff).length,status:x.status,url:x.feed.url})),{name:"Reddit",discovered:redditItems.length,status:redditItems.length?"connected":"unavailable",url:"https://www.reddit.com/"}],generatedAt:new Date().toISOString(),windowHours:MAX_AGE_HOURS}}
