import { NextResponse } from "next/server";
import { generateWithLLM } from "../../../lib/llm";
import { runMultiAgentResearch } from "../../../lib/multi-agent";
import { filterPreviouslyCovered, filterGeneratedDuplicates, rememberCandidates, saveGeneratedStories } from "../../../lib/content-memory";

export const runtime = "nodejs";
export const maxDuration = 60;

type SourceDetail = { name: string; url: string; published_at: string };
type ClientProfile = { name?: string; description?: string; sector?: string; chains?: string; topics?: string; competitors?: string; audience?: string; tone?: string; objectives?: string; avoid?: string };
type Story = { headline:string; category:string; score:number; format:"thread"|"single post"; reason:string; summary:string; keywords:string[]; hashtags:string[]; sources:string[]; source_details?:SourceDetail[]; posting_time_utc:string; cta:string; graphic_prompt:string; alt_text:string; thread:{title:string;tweets:string[]}; engagement:{reply:string;quote_tweet:string;poll:string;blog_expansion:string}; candidate_ids:string[] };
type FreshCandidate = { id:string; title:string; url:string; source:string; publishedAt:string; summary:string; category:string; keywords:string[]; score:number; opportunity:string };
type GenerateBody = { provider?:string; clientProfile?:ClientProfile };

const CONTENT_PROMPT = `You are the Web3 Pulse Content Director Agent. Work ONLY from the supplied VERIFIED CURRENT candidates. NEVER recreate an event from model memory. Every story must use exactly ONE candidate_id. Never use the same candidate_id twice. Never produce two stories about the same real-world event, protocol incident, claim, announcement or news event. If candidates describe the same event from different sources, treat them as ONE event. Return as many distinct stories as the supplied eligible candidates allow, up to five. Prefer event diversity over category repetition. Preserve supplied source URLs. Every story must be traceable to its assigned candidate. Generate the complete content package. Never invent airdrop eligibility, tasks, claim links, rewards or deadlines. Never invent security-incident users, losses, attacker identity or remediation. Return ONLY valid JSON with a stories array.`;
function clientContext(client?:ClientProfile){if(!client)return "";return ["","CLIENT PROFILE",`Name: ${client.name||""}`,`Description: ${client.description||""}`,`Sector: ${client.sector||""}`,`Chains/ecosystems: ${client.chains||""}`,`Priority topics: ${client.topics||""}`,`Competitors: ${client.competitors||""}`,`Audience: ${client.audience||""}`,`Tone: ${client.tone||""}`,`PR objectives: ${client.objectives||""}`,`Avoid/guardrails: ${client.avoid||""}`].join("\n");}
function normalizeUrl(url:string){return String(url||"").trim().replace(/\/$/,"");}
function resolveCandidateIds(story:any,candidates:FreshCandidate[],fallbackIndex?:number):string[]{const byId=new Map(candidates.map(c=>[c.id,c]));const explicit=Array.isArray(story?.candidate_ids)?story.candidate_ids:[story?.candidate_id];const ids=explicit.filter((id:unknown)=>typeof id==="string"&&byId.has(id));if(ids.length)return [ids[0]];const urls=new Set<string>();if(Array.isArray(story?.sources))for(const url of story.sources)if(typeof url==="string")urls.add(normalizeUrl(url));if(Array.isArray(story?.source_details))for(const detail of story.source_details)if(typeof detail?.url==="string")urls.add(normalizeUrl(detail.url));const urlMatch=candidates.find(c=>urls.has(normalizeUrl(c.url)));if(urlMatch)return [urlMatch.id];const headline=String(story?.headline||story?.thread?.title||"");if(headline){const exact=candidates.find(c=>c.title.trim().toLowerCase()===headline.trim().toLowerCase());if(exact)return [exact.id];}if(typeof fallbackIndex==="number"&&candidates[fallbackIndex])return [candidates[fallbackIndex].id];return [];}
function normalizeStory(story:any,candidates:FreshCandidate[],fallbackIndex?:number):Story|null{const ids=resolveCandidateIds(story,candidates,fallbackIndex);if(ids.length!==1)return null;const first=candidates.find(c=>c.id===ids[0]);if(!first)return null;const threadSource=story?.thread&&typeof story.thread==="object"?story.thread:{};const engagement=story?.engagement&&typeof story.engagement==="object"?story.engagement:{};const tweets=Array.isArray(threadSource.tweets)?threadSource.tweets.filter((x:unknown)=>typeof x==="string"&&x.trim()) as string[]:[];const sourceDetails:SourceDetail[]=[{name:first.source,url:first.url,published_at:first.publishedAt}];return {headline:String(story?.headline||first.title),category:String(story?.category||first.category||"Emerging"),score:Number.isFinite(Number(story?.score))?Number(story.score):first.score,format:story?.format==="single post"?"single post":"thread",reason:String(story?.reason||first.opportunity||"Current verified Web3 development."),summary:String(story?.summary||first.summary||""),keywords:Array.isArray(story?.keywords)?story.keywords.filter((x:unknown)=>typeof x==="string") as string[]:first.keywords||[],hashtags:Array.isArray(story?.hashtags)?story.hashtags.filter((x:unknown)=>typeof x==="string") as string[]:[],sources:[first.url],source_details:sourceDetails,posting_time_utc:String(story?.posting_time_utc||first.publishedAt),cta:String(story?.cta||"Review the source before publishing."),graphic_prompt:String(story?.graphic_prompt||`Create a premium editorial Web3 visual for: ${story?.headline||first.title}.`),alt_text:String(story?.alt_text||`Editorial visual representing ${story?.headline||first.title}.`),thread:{title:String(threadSource.title||story?.headline||first.title),tweets:tweets.length?tweets:[String(story?.summary||first.summary||story?.headline||first.title)]},engagement:{reply:String(engagement.reply||""),quote_tweet:String(engagement.quote_tweet||""),poll:String(engagement.poll||""),blog_expansion:String(engagement.blog_expansion||"")},candidate_ids:ids};}
function parseLLMJson(content:string):any{const cleaned=content.replace(/^\s*```(?:json)?\s*/i,"").replace(/\s*```\s*$/i,"").trim();try{return JSON.parse(cleaned);}catch{}const start=cleaned.indexOf("{");if(start<0)throw new Error("LLM returned no JSON object.");let depth=0,inString=false,escaped=false;for(let i=start;i<cleaned.length;i++){const ch=cleaned[i];if(inString){if(escaped)escaped=false;else if(ch==="\\")escaped=true;else if(ch==='"')inString=false;continue;}if(ch==='"'){inString=true;continue;}if(ch==="{")depth++;else if(ch==="}"&&--depth===0){try{return JSON.parse(cleaned.slice(start,i+1));}catch{break;}}}throw new Error("LLM returned invalid JSON.");}

export async function POST(request:Request){
  const started=Date.now();
  try{
    let body:GenerateBody={};try{body=await request.json();}catch{}
    const provider=["auto","gemini","nemotron","openrouter"].includes(body.provider||"")?(body.provider as "auto"|"gemini"|"nemotron"|"openrouter"):"auto";
    const now=new Date();const currentDate=now.toISOString().slice(0,10);const cutoffUtc=new Date(now.getTime()-72*60*60*1000).toISOString();
    try{
      const packet=await runMultiAgentResearch([]);
      let candidates:FreshCandidate[]=packet.candidates.filter(item=>{const t=Date.parse(item.publishedAt);return Number.isFinite(t)&&t>=Date.parse(cutoffUtc)&&t<=now.getTime();}).map(item=>({id:item.id,title:item.title,url:item.url,source:item.source,publishedAt:item.publishedAt,summary:item.summary,category:item.category,keywords:item.keywords,score:item.scores.overall,opportunity:item.opportunity}));
      const rawCandidateCount=candidates.length;
      await rememberCandidates(candidates);
      candidates=await filterPreviouslyCovered(candidates);
      const memoryFilteredCount=candidates.length;
      // Do not apply browser/client exclusion state. Persistent editorial memory is authoritative.
      // Candidate diversity is based only on unique candidate IDs; fuzzy title matching here was too aggressive.
      const diverse:FreshCandidate[]=Array.from(new Map(candidates.sort((a,b)=>b.score-a.score).map(c=>[c.id,c])).values()).slice(0,40);
      console.info("Web3 Pulse briefing gate",{rawCandidateCount,memoryFilteredCount,diverseCount:diverse.length,historyGuard:"exact-url-or-headline",elapsed_ms:Date.now()-started});
      if(!diverse.length)return NextResponse.json({date:currentDate,generated_at_utc:now.toISOString(),stories:[],no_new_stories:true,code:"NO_NEW_STORIES",error:"No previously-uncovered verified stories are available. Nothing old was reused.",diagnostics:{raw_candidates:rawCandidateCount,after_memory_filter:memoryFilteredCount,diverse_candidates:0},cutoff_utc:cutoffUtc,memory:"supabase"},{status:200});
      const targetCount=Math.min(5,diverse.length);
      const context=[`CURRENT_DATE: ${currentDate}`,`CURRENT_TIME_UTC: ${now.toISOString()}`,`CUTOFF_UTC: ${cutoffUtc}`,"Only supplied candidates are valid facts.",`CANDIDATES: ${JSON.stringify(diverse.slice(0,Math.max(10,targetCount)),null,2)}`].join("\n");
      const candidateContext=`MANDATORY: generate up to ${targetCount} stories. Each story MUST have exactly one candidate_id. Candidate IDs MUST be unique. Do not create multiple angles from one event. If fewer genuinely distinct events exist, return fewer stories rather than repeating an event.`;
      const userPrompt=`${context}\n${candidateContext}\nGenerate the COMPLETE CONTENT PACKAGE.`+clientContext(body.clientProfile);
      let generation=await generateWithLLM({provider,system:CONTENT_PROMPT,user:userPrompt,responseFormat:"json_object",temperature:0.35});
      let data:any;try{data=parseLLMJson(generation.content);}catch{return NextResponse.json({error:"The selected LLM returned malformed structured output.",code:"INVALID_LLM_JSON",provider:generation.provider,model:generation.model},{status:502});}
      let rawStories=Array.isArray(data.stories)?data.stories:[];
      let stories:Story[]=rawStories.map((s:any,i:number)=>normalizeStory(s,diverse,i)).filter((s:Story|null):s is Story=>s!==null);
      stories=await filterGeneratedDuplicates(stories);
      if(stories.length<targetCount){
        const used=new Set<string>(stories.flatMap((s:Story)=>s.candidate_ids));
        const remaining=diverse.filter(c=>!used.has(c.id)).slice(0,targetCount-stories.length);
        if(remaining.length){const retry=`${context}\nRETRY: Generate exactly ${remaining.length} NEW stories using ONLY these unused candidate IDs: ${remaining.map(c=>c.id).join(", ")}. One unique candidate_id per story. Do not reuse any event already represented. Return ONLY JSON with stories.`;try{generation=await generateWithLLM({provider,system:CONTENT_PROMPT,user:retry,responseFormat:"json_object",temperature:0.45});data=parseLLMJson(generation.content);rawStories=Array.isArray(data.stories)?data.stories:[];const retryStories=rawStories.map((s:any,i:number)=>normalizeStory(s,remaining,i)).filter((s:Story|null):s is Story=>s!==null);stories=await filterGeneratedDuplicates([...stories,...retryStories]);}catch(error){console.warn("Duplicate-safe retry failed",error);}}
      }
      if(!stories.length)return NextResponse.json({date:currentDate,generated_at_utc:now.toISOString(),stories:[],no_new_stories:true,code:"DUPLICATE_GUARD_BLOCKED",error:"No genuinely new stories survived the duplicate guard. Nothing old was returned.",diagnostics:{raw_candidates:rawCandidateCount,after_memory_filter:memoryFilteredCount,diverse_candidates:diverse.length,llm_stories:rawStories.length},candidate_count:diverse.length,memory:"supabase"},{status:200});
      try{await saveGeneratedStories(stories.map(story=>({headline:story.headline,category:story.category,candidate_ids:story.candidate_ids,source_urls:story.sources,content:story,status:"generated",generated_at:now.toISOString(),llm_provider:generation.provider,llm_model:generation.model})))}catch(error){return NextResponse.json({error:"Persistent content memory could not be written. Nothing was returned to prevent duplicates.",code:"MEMORY_WRITE_FAILED",detail:error instanceof Error?error.message:"Supabase write failed"},{status:503});}
      return NextResponse.json({...data,date:currentDate,generated_at_utc:now.toISOString(),stories,research_window:{cutoff_utc:cutoffUtc,hours:72,candidate_count:diverse.length},llm_provider:generation.provider,llm_model:generation.model,client_mode:Boolean(body.clientProfile),client_name:body.clientProfile?.name||null,llm_calls:2,elapsed_ms:Date.now()-started,memory:"supabase"});
    }catch(error){console.error("Duplicate memory/research gate failed:",error);return NextResponse.json({error:"Persistent duplicate protection is unavailable. Generation was blocked so an old story cannot be shown again.",code:"MEMORY_REQUIRED",detail:error instanceof Error?error.message:"Memory unavailable",elapsed_ms:Date.now()-started},{status:503});}
  }catch(error:any){console.error("Web3 Pulse Generation Error:",error);return NextResponse.json({error:error?.message||"Failed to generate current Web3 Pulse intelligence.",code:"GENERATION_ERROR",elapsed_ms:Date.now()-started},{status:500});}
}