"use client";

import { useState } from "react";
import { Activity, AlertCircle, ArrowUpRight, CheckCircle2, Clock3, ExternalLink, Flame, RefreshCw, Search, ShieldCheck, Sparkles, TrendingUp, Zap } from "lucide-react";
import Link from "next/link";

type Item={id:string;title:string;url:string;source:string;publishedAt:string;summary:string;category:string;keywords:string[];entities:string[];scores:{relevance:number;momentum:number;novelty:number;credibility:number;prPotential:number;overall:number};opportunity:string};
type Narrative={name:string;count:number;score:number;momentum:number;keywords:string[];stories:string[]};
type Result={items:Item[];narratives:Narrative[];sources:{name:string;discovered:number;status:string}[];generatedAt:string};

export default function ResearchPage(){
 const [result,setResult]=useState<Result|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 const run=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/research",{method:"POST",cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Research failed");setResult(j)}catch(e){setError(e instanceof Error?e.message:"Research failed")}finally{setLoading(false)}};
 return <main className="research-page"><div className="research-top"><div><Link href="/" className="research-back">← CryptoPulse</Link><div className="research-kicker"><Sparkles size={13}/> Intelligence layer</div><h1>Research Engine</h1><p>Discover, verify, score and cluster the conversations worth turning into content.</p></div><button className="research-run" onClick={run} disabled={loading}><RefreshCw size={15} className={loading?"spin":""}/>{loading?"Researching…":"Run fresh research"}</button></div>
 {error&&<div className="research-error"><AlertCircle size={17}/><div><strong>Research failed</strong><p>{error}</p></div></div>}
 {!result&&!loading&&<div className="research-empty"><div className="research-empty-icon"><Search size={28}/></div><h2>Start a research run</h2><p>CryptoPulse will scan connected crypto news feeds, remove duplicates, classify stories, score opportunities and detect emerging narratives.</p><button className="research-run" onClick={run}><Zap size={15}/> Start research</button></div>}
 {loading&&<div className="research-loading"><div className="research-loader"><RefreshCw size={26} className="spin"/></div><h2>Researching the ecosystem…</h2><p>Discovering stories → deduplicating → scoring → detecting narratives</p></div>}
 {result&&!loading&&<><section className="research-metrics"><Metric icon={<Search/>} value={result.items.length} label="Unique stories"/><Metric icon={<TrendingUp/>} value={result.narratives.length} label="Narratives"/><Metric icon={<Flame/>} value={result.items.filter(x=>x.scores.overall>=85).length} label="High-value"/><Metric icon={<ShieldCheck/>} value={result.sources.filter(x=>x.status==="connected").length+"/"+result.sources.length} label="Sources online"/></section>
 <section className="research-grid"><div><div className="research-section-title"><div><h2>Top opportunities</h2><p>Ranked by relevance, momentum, novelty, credibility and PR potential.</p></div><span>{new Date(result.generatedAt).toLocaleTimeString()}</span></div>{result.items.map((item,i)=><article className="research-story" key={item.id}><div className="research-rank">{String(i+1).padStart(2,"0")}</div><div className="research-story-body"><div className="research-tags"><b>{item.category}</b><span>{item.source}</span><span><Clock3 size={10}/>{new Date(item.publishedAt).toLocaleDateString()}</span></div><h3>{item.title}</h3><p>{item.summary}</p><div className="research-scores"><Score label="Overall" value={item.scores.overall}/><Score label="Momentum" value={item.scores.momentum}/><Score label="PR" value={item.scores.prPotential}/><Score label="Credibility" value={item.scores.credibility}/></div><div className="research-opportunity"><Zap size={13}/><span>{item.opportunity}</span>{item.entities.length>0&&<small>{item.entities.join(" · ")}</small>}</div><a href={item.url} target="_blank" rel="noreferrer" className="research-source">Open source <ExternalLink size={11}/></a></div></article>)}</div>
 <aside><div className="research-panel"><div className="panel-title"><TrendingUp size={15}/> Narrative radar</div><p>Clusters emerging from today's research.</p>{result.narratives.map(n=><div className="narrative-row" key={n.name}><div className="narrative-head"><b>{n.name}</b><strong>{n.score}</strong></div><div className="narrative-bar"><i style={{width:`${Math.min(n.score,100)}%`}}/></div><small>{n.count} stories · momentum {n.momentum}</small><div className="research-keywords">{n.keywords.slice(0,4).map(k=><span key={k}>{k}</span>)}</div></div>)}</div><div className="research-panel"><div className="panel-title"><Activity size={15}/> Source health</div>{result.sources.map(s=><div className="source-row" key={s.name}><div><b>{s.name}</b><small>{s.discovered} discovered</small></div>{s.status==="connected"?<CheckCircle2 size={16}/>:<AlertCircle size={16}/>}</div>)}</div><div className="research-panel research-note"><div className="panel-title"><ShieldCheck size={15}/> Verification principle</div><p>Research results are signals, not automatic truth. Review sources before using a claim in public-facing content. CryptoPulse keeps publishing manual.</p></div></aside></section></>}
 </main>
}
function Metric({icon,value,label}:{icon:any;value:any;label:string}){return <div className="research-metric"><span>{icon}</span><strong>{value}</strong><small>{label}</small></div>}
function Score({label,value}:{label:string;value:number}){return <div><small>{label}</small><b>{value}</b></div>}
