"use client";

import { useEffect, useMemo, useState } from "react";

type Channel = { id:string; name:string; displayName:string|null; descriptor:string; service:string; avatar:string; isDisconnected:boolean; isLocked:boolean; isQueuePaused:boolean; externalLink:string|null };
type Workspace = { organization:{id:string;name:string;channelCount:number;limits:{channels:number;scheduledPosts:number}}|null; channels:Channel[]; plan:string; planSource:string; account:{name:string;timezone:string} };

const supported = ["twitter","facebook","linkedin","threads","pinterest"];
const labels:Record<string,string>={twitter:"X",facebook:"Facebook",linkedin:"LinkedIn",threads:"Threads",pinterest:"Pinterest"};

function makeVariant(text:string, service:string){
  const clean=text.trim();
  if(service==="twitter") return clean.length>280?clean.slice(0,276)+"…":clean;
  if(service==="threads") return clean.length>500?clean.slice(0,496)+"…":clean;
  if(service==="linkedin") return `${clean}\n\nWhat do you think?`;
  if(service==="facebook") return clean;
  if(service==="pinterest") return `${clean}\n\nExplore the full story and save this for later.`;
  return clean;
}

export default function PublishPage(){
 const [workspace,setWorkspace]=useState<Workspace|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[source,setSource]=useState(""),[variants,setVariants]=useState<Record<string,string>>({}),[selected,setSelected]=useState<string[]>([]),[publishing,setPublishing]=useState(false),[result,setResult]=useState<string[]>([]),[mode,setMode]=useState<"shareNow"|"addToQueue">("addToQueue");
 useEffect(()=>{fetch("/api/buffer/channels").then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to connect to Buffer");setWorkspace(j);const eligible=(j.channels||[]).filter((c:Channel)=>supported.includes(c.service)&&!c.isDisconnected&&!c.isLocked);setSelected(eligible.slice(0,Math.min(3,eligible.length)).map((c:Channel)=>c.id));}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const eligible=useMemo(()=>workspace?.channels.filter(c=>supported.includes(c.service)&&!c.isDisconnected&&!c.isLocked)||[],[workspace]);
 const unsupported=useMemo(()=>workspace?.channels.filter(c=>!supported.includes(c.service))||[],[workspace]);
 const toggle=(id:string)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):x.length>=3?x:[...x,id]);
 const build=()=>{const next:Record<string,string>={};eligible.forEach(c=>next[c.id]=makeVariant(source,c.service));setVariants(next);};
 const publish=async()=>{setPublishing(true);setResult([]);const messages:string[]=[];for(const id of selected){const ch=eligible.find(c=>c.id===id);if(!ch)continue;try{const r=await fetch("/api/buffer/publish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({channelId:id,text:variants[id]||source,mode})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Failed");messages.push(`${labels[ch.service]||ch.service}: ${mode==="shareNow"?"published":"added to queue"}`);}catch(e){messages.push(`${labels[ch.service]||ch.service}: ${e instanceof Error?e.message:"failed"}`);}}setResult(messages);setPublishing(false);};
 return <main style={{minHeight:"100vh",background:"#f6f8fb",color:"#172033",fontFamily:"Inter,system-ui,sans-serif",padding:"32px"}}><div style={{maxWidth:1100,margin:"0 auto"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",marginBottom:24}}><div><div style={{fontSize:11,fontWeight:800,letterSpacing:1.5,color:"#0ea5b7",textTransform:"uppercase"}}>Publishing layer</div><h1 style={{fontSize:32,margin:"7px 0"}}>Buffer Control Center</h1><p style={{margin:0,color:"#68758a"}}>CryptoPulse detects your Buffer setup and prepares platform-specific content for the channels you actually have connected.</p></div><a href="/" style={{textDecoration:"none",background:"white",border:"1px solid #dce3ec",borderRadius:10,padding:"10px 14px",color:"#405069",fontWeight:700,fontSize:12}}>← Dashboard</a></div>
  {loading&&<Card><h3>Connecting to Buffer…</h3><p>Detecting your organization, plan limits and connected social channels.</p></Card>}
  {error&&<Card><h3>Buffer connection needed</h3><p style={{color:"#b42318"}}>{error}</p><p>Add <b>BUFFER_API_KEY</b> to Vercel Environment Variables, then redeploy.</p><a href="https://buffer.com" target="_blank" rel="noreferrer">Open Buffer →</a></Card>}
  {workspace&&!loading&&<>
   <section style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginBottom:18}}><Stat title="Detected plan" value={workspace.plan}/><Stat title="Channel limit" value={String(workspace.organization?.limits.channels??"—")}/><Stat title="Connected" value={String(workspace.channels.length)}/><Stat title="Publishing targets" value={`${selected.length}/3`}/></section>
   <Card><div style={{display:"flex",justifyContent:"space-between",gap:15,alignItems:"center"}}><div><h2 style={{margin:0,fontSize:18}}>Connected channels</h2><p style={{margin:"5px 0 0",color:"#68758a",fontSize:12}}>Free Buffer supports up to 3 connected channels. CryptoPulse will never send to a fourth target.</p></div><span style={{fontSize:10,color:"#68758a"}}>{workspace.planSource}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:16}}>{workspace.channels.map(c=>{const active=selected.includes(c.id),supportedChannel=supported.includes(c.service),disabled=!supportedChannel||c.isDisconnected||c.isLocked;return <button key={c.id} onClick={()=>toggle(c.id)} disabled={disabled} style={{textAlign:"left",border:`1px solid ${active?"#0ea5b7":"#dce3ec"}`,background:active?"#ecfeff":"white",borderRadius:14,padding:13,opacity:disabled?.55:1,cursor:disabled?"not-allowed":"pointer"}}><div style={{display:"flex",justifyContent:"space-between"}}><b>{labels[c.service]||c.service}</b><span>{active?"✓":""}</span></div><div style={{fontSize:11,color:"#68758a",marginTop:5}}>{c.displayName||c.name}</div><div style={{fontSize:9,color:c.isLocked?"#b42318":"#7b8798",marginTop:8}}>{c.isLocked?"Locked":c.isDisconnected?"Disconnected":supportedChannel?"Available":"Not used by CryptoPulse"}</div></button>})}</div>{unsupported.length>0&&<p style={{fontSize:11,color:"#7b8798",marginBottom:0}}>Other connected channels remain visible but are not selected because this publishing workflow is limited to X, Facebook, Threads, LinkedIn and Pinterest.</p>}</Card>
   <Card><h2 style={{margin:"0 0 6px",fontSize:18}}>Create content for every detected platform</h2><p style={{margin:"0 0 14px",color:"#68758a",fontSize:12}}>Paste a master draft from Content Studio. CryptoPulse adapts it to every eligible connected platform; only your selected 3 can be published.</p><textarea value={source} onChange={e=>setSource(e.target.value)} placeholder="Paste your master post or thread opener here…" style={{width:"100%",minHeight:130,border:"1px solid #dce3ec",borderRadius:12,padding:13,resize:"vertical",outline:"none",fontSize:13}}/><div style={{display:"flex",justifyContent:"space-between",marginTop:10}}><span style={{fontSize:10,color:"#7b8798"}}>Selected targets: {selected.length}/3</span><button onClick={build} disabled={!source.trim()} style={button(true)}>Generate platform variants</button></div></Card>
   {eligible.length>0&&<Card><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><div><h2 style={{margin:0,fontSize:18}}>Platform content</h2><p style={{margin:"5px 0 0",fontSize:11,color:"#68758a"}}>Edit before sending to Buffer.</p></div></div>{eligible.map(c=><div key={c.id} style={{border:"1px solid #e1e7ef",borderRadius:13,padding:12,marginBottom:10,background:selected.includes(c.id)?"#fbfeff":"#fafbfc"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><b>{labels[c.service]||c.service}</b><span style={{fontSize:10,color:selected.includes(c.id)?"#0b8b9b":"#7b8798"}}>{selected.includes(c.id)?"Publishing target":"Content only"}</span></div><textarea value={variants[c.id]??""} onChange={e=>setVariants(v=>({...v,[c.id]:e.target.value}))} placeholder="Generate variants above…" style={{width:"100%",minHeight:100,border:"1px solid #dce3ec",borderRadius:10,padding:10,resize:"vertical",fontSize:12}}/></div>)}<div style={{display:"flex",flexWrap:"wrap",gap:8,alignItems:"center",marginTop:12}}><select value={mode} onChange={e=>setMode(e.target.value as "shareNow"|"addToQueue")} style={{border:"1px solid #dce3ec",background:"white",borderRadius:9,padding:"9px 10px",fontSize:11}}><option value="addToQueue">Add to Buffer queue</option><option value="shareNow">Publish now</option></select><button onClick={publish} disabled={publishing||selected.length===0||!source.trim()} style={button(true)}>{publishing?"Sending…":mode==="shareNow"?"Publish selected 3":"Send selected 3 to Buffer"}</button></div>{result.length>0&&<div style={{marginTop:14,padding:12,borderRadius:10,background:"#f0fdf4",color:"#166534",fontSize:11}}>{result.map((r,i)=><div key={i}>{r}</div>)}</div>}</Card>}
  </>}
 </div></main>
}
function Card({children}:{children:React.ReactNode}){return <section style={{background:"white",border:"1px solid #dfe5ed",borderRadius:18,padding:20,marginBottom:14,boxShadow:"0 8px 30px rgba(20,40,70,.05)"}}>{children}</section>}
function Stat({title,value}:{title:string;value:string}){return <div style={{background:"white",border:"1px solid #dfe5ed",borderRadius:14,padding:14}}><div style={{fontSize:9,color:"#7b8798",textTransform:"uppercase",letterSpacing:1,fontWeight:800}}>{title}</div><div style={{fontSize:18,fontWeight:850,marginTop:7}}>{value}</div></div>}
function button(primary:boolean){return {border:0,borderRadius:9,padding:"10px 14px",fontSize:11,fontWeight:800,cursor:"pointer",background:primary?"#0f9fb1":"white",color:primary?"white":"#405069"};}
