import { NextResponse } from "next/server";
import { generateWithLLM } from "../../../lib/llm";

export const runtime = "nodejs";
export const maxDuration = 60;

type Candidate = { id:string; title:string; url:string; source:string; publishedAt:string; summary:string; category:string; keywords:string[]; score:number; opportunity:string };

const SYSTEM = `You are Web3 Pulse's senior crypto journalist and elite X thread writer. Turn the supplied source into sharp, original, publication-ready social content. The output will be posted directly to X after editorial review. NEVER write instructions to the editor, publisher or reader about publishing, verifying, checking sources, reviewing, formatting or what to do next. Do not mention this prompt, the generation process, AI, or content workflow.

THREAD STANDARD: exactly 5 posts, each under 280 characters. Make it read like a strong human-written crypto news thread, not a source summary.
1) HOOK — an intriguing fact, tension, consequence or sharp observation. Do not copy the source headline.
2) FACTS — the most important concrete development from the source.
3) WHY IT MATTERS — explain the immediate significance for the crypto ecosystem, users, markets, builders or investors.
4) CONTEXT — add useful context, comparison, second-order implication or a detail readers may miss.
5) TAKEAWAY — a strong closing insight or forward-looking implication. This must be actual editorial content, never a publishing instruction, source reminder or generic CTA.

Every post must add new information. Use natural prose and varied sentence structure. No filler, generic introductions, hype without evidence, repeated headlines, or AI clichés. Do not put the source URL in the tweets; it is stored separately in metadata. Return ONLY valid JSON with a stories array containing exactly one story.`;

function cleanHtml(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/\s+/g," ").trim();}
function meta(html:string,name:string){const r=new RegExp(`<meta[^>]+(?:name|property)=["']${name}["'][^>]+content=["']([^"']+)["'][^>]*>`,'i');return html.match(r)?.[1]||"";}
function titleFrom(html:string){return meta(html,"og:title")||meta(html,"twitter:title")||html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/<[^>]+>/g," ").trim()||"Source development";}
function sourceName(url:string){try{return new URL(url).hostname.replace(/^www\./,"");}catch{return "Source";}}
function quality(tweets:string[]){if(tweets.length!==5||tweets.some(x=>x.length<45||x.length>280))return false;const n=tweets.map(x=>x.toLowerCase().replace(/[^a-z0-9 ]/g," ").replace(/\s+/g," ").trim());if(new Set(n).size!==n.length)return false;const forbidden=/(before publishing|before you publish|verify (the|this|the original)|read (the|our) (source|article)|check the source|review (the|this) (thread|post)|publishing instructions|content workflow|generated content|ai generated|as an ai|source: https?:\/\/|click the link|link in bio|what to do next)/i;return !tweets.some(x=>forbidden.test(x))&&!/^(here's what you need to know|in a major development|this is huge|the crypto world)/i.test(tweets[0]);}
function fallback(c:Candidate){const t=c.title,s=c.summary,w=c.opportunity;const tweets=[`A notable Web3 development: ${t}`,`The key facts: ${s}`,`Why it matters: ${w}`,`The broader implication is worth watching as this develops across the ${c.category} landscape.`,`The takeaway: the next signals will show whether this becomes a lasting shift or a short-lived event.`].map(x=>x.slice(0,280));return {headline:t,category:c.category,score:70,format:"thread",reason:w,summary:s,keywords:c.keywords,hashtags:[],sources:[c.url],source_details:[{name:c.source,url:c.url,published_at:c.publishedAt}],posting_time_utc:c.publishedAt,cta:"",graphic_prompt:`Premium editorial Web3 visual about: ${t}`,alt_text:`Editorial visual about ${t}`,thread:{title:t,tweets},engagement:{reply:"",quote_tweet:"",poll:"",blog_expansion:""},candidate_ids:[c.id],degraded:true};}
function parse(content:string){const x=content.replace(/^\s*```(?:json)?\s*/i,"").replace(/\s*```\s*$/i,"").trim();try{return JSON.parse(x)}catch{}const a=x.indexOf("{");const b=x.lastIndexOf("}");if(a>=0&&b>a)return JSON.parse(x.slice(a,b+1));throw new Error("The model returned invalid JSON.");}

export async function POST(request:Request){try{const body=await request.json().catch(()=>({}));const raw=String(body?.url||"").trim();if(!/^https?:\/\//i.test(raw))return NextResponse.json({error:"Please paste a valid http(s) article URL."},{status:400});const url=new URL(raw).toString();const r=await fetch(url,{cache:"no-store",headers:{"User-Agent":"Mozilla/5.0 (compatible; Web3Pulse/1.0; +https://vercel.com)"}});if(!r.ok)throw new Error(`The source returned HTTP ${r.status}. Try the original article URL or another public source.`);const html=await r.text();const title=titleFrom(html).slice(0,240);const text=cleanHtml(html).slice(0,14000);if(text.length<120)throw new Error("Could not extract enough readable text from that page. Try a public article page.");const candidate:Candidate={id:`url:${Buffer.from(url).toString("base64url").slice(0,40)}`,title,url,source:sourceName(url),publishedAt:new Date().toISOString(),summary:text,category:/bitcoin|btc/i.test(`${title} ${text}`)?"Bitcoin":/ethereum|eth|layer 2|l2/i.test(`${title} ${text}`)?"Ethereum":/defi|dex|stablecoin|yield/i.test(`${title} ${text}`)?"DeFi":"Emerging",keywords:[],score:80,opportunity:"Assess the reported development, its immediate implications and the strongest credible second-order effect described by the source."};try{const result=await generateWithLLM({provider:"auto",system:SYSTEM,user:`VERIFIED SOURCE:\n${JSON.stringify(candidate,null,2)}`,responseFormat:"json_object",temperature:0.35,maxTokens:2200});const data=parse(result.content);const story=data?.stories?.[0];const tweets=Array.isArray(story?.thread?.tweets)?story.thread.tweets.slice(0,5).map((x:any)=>String(x).trim()):[];if(!story||!quality(tweets))throw new Error("The generated thread did not meet the publication quality standard.");story.sources=[url];story.source_details=[{name:candidate.source,url,published_at:candidate.publishedAt}];story.candidate_ids=[candidate.id];story.thread={title:String(story.thread?.title||story.headline||title),tweets};story.cta="";return NextResponse.json({generated_at_utc:new Date().toISOString(),stories:[story],source:{title,url,name:candidate.source},degraded:Boolean(result.provider==="fallback")});}catch{return NextResponse.json({generated_at_utc:new Date().toISOString(),stories:[fallback(candidate)],source:{title,url,name:candidate.source},degraded:true});}}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to process this URL."},{status:502});}}
